# DCF Study material deployment
name: Dcf Computer Science Resources

# Trigger to Execute this action
on:
  push: 
      branches: [main]
  workflow_dispatch:

# Global Permissions require to execute actions
permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

# Jobs inside the action
jobs:
  # Name of the job-1
  deploy-page: 
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # GitHub runner to execute this actions
    runs-on: ubuntu-latest
    # Steps to execute this action
    steps:
        # Step 1
      - name: Code Checkout
        uses: actions/checkout@v4

        # Step 2
      - name: Setup Pages
        uses: actions/configure-pages@v4
  
        # Step 3
      - name: Upload static files
        with:
          path: "."
        uses: actions/upload-pages-artifact@v4 
  
          # Step 4
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
            
        
